import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css"
import "@/styles/tokens.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <main
      style={{
          backgroundColor: "var(--background-dark)",
            color: "var(--color-light-green)",
            minHeight: "100vh",
      }}>
          <h1>truc des enigmes</h1>
          <div>
              {children}
          </div>
      </main>
  );
}
