import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
    <body style={{
      backgroundColor: "var(--color-dark)"
    }} className="text-white antialiased">
        {children}
    </body>
    </html>
  );
}
